#!/bin/bash

# Run the CNN training

RATIO=0.8
LIMIT=800
BATCH=400
EPOCH=100

rm data/out/*
rm data/unfiltered/*

python3 loader.py --train --limit $LIMIT --ratio $RATIO --batch $BATCH --epoch $EPOCH

echo "======== FINISHED ========"